#.travis.yml

language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - rm -R ./node_modules/ngx-socket-io/node_modules   
  - ng build --prod --configuration=production

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change